import React from "react";
import { Image, Text, TouchableOpacity, View, NativeModules, LayoutAnimation, DeviceEventEmitter } from 'react-native';
import { NetConnectionModal } from './components/NetConnectionModal';
import { AnimatedView } from './components/AnimatedView';
import { styles } from '../style/styles';
import { cartUrl, cartItemsUrl } from "../data/settings";

const { NativeStorage } = NativeModules;

export default class Product extends React.PureComponent {

	componentDidMount() {
		const PushNotificationAndroid = require('react-native-push-notification');
		(function() {
			// Register all the valid actions for notifications here and add the action handler for each action
			PushNotificationAndroid.registerNotificationActions(['Accept','Reject','Yes','No']);
			DeviceEventEmitter.addListener('notificationActionReceived', function(action){
				console.log ('Notification action received: ' + action);
				const info = JSON.parse(action.dataJSON);
				if (info.action == 'Accept') {
					this.props.navigation.navigate('Cart')
				} else if (info.action == 'Reject') {
					// Do work pertaining to Reject action here
				}
				// Add all the required actions handlers
			});
		})();
	}

	showNotification(title, text, shortText) {
		const PushNotification = require('react-native-push-notification');

		PushNotification.localNotification({
			id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
			ticker: "My Notification Ticker", // (optional)
			autoCancel: false, // (optional) default: true
			largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
			smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
			bigText: text, // (optional) default: "message" prop
			subText: '', // (optional) default: none
			color: "red", // (optional) default: system default
			vibrate: true, // (optional) default: true
			vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
			tag: 'some_tag', // (optional) add tag to message
			group: "group", // (optional) add group to message
			ongoing: false, // (optional) set whether this is an "ongoing" notification
			priority: "high", // (optional) set notification priority, default: high
			visibility: "private", // (optional) set notification visibility, default: private
			importance: "high", // (optional) set notification importance, default: high
			title: title, // (optional)
			message: shortText, // (required)
			playSound: false, // (optional) default: true
			soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
			repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
			actions: '["Yes", "No"]'  // (Android only) See the doc for notification actions to know more});
		});
	}

	handleOpenProductList = () => {
		this.props.navigation.navigate('ProductsList')
	};

	handleAddToCart = async () => {
		const { navigation } = this.props;
		const item = navigation.getParam('item', {});
		const content = await NativeStorage.getItem() || '{}';
		const response = JSON.parse(content);
		const headers = new Headers();

		headers.append('Content-Type', 'application/json');
		headers.append('Authorization', `Bearer ${response.token}`);

		const cartString = await fetch(cartUrl, {
			method: 'GET',
			headers
		});

		if (cartString.status === 200) {
			const addToCartResponse = await fetch(cartItemsUrl, {
				method: 'POST',
				headers,
				body: JSON.stringify({
					cartItem: {
						quote_id: (JSON.parse(cartString._bodyText)).id,
						qty: 1,
						sku: item.sku
					}
				})
			});

			const cartResponse = JSON.parse(addToCartResponse._bodyText);
			if (cartResponse.message) {
				this.showNotification('Product NOT added', cartResponse.message, 'Product cannot be added');
			} else {
				this.showNotification('Product is added to cart', 'Product is added', `${cartResponse.qty} of ${cartResponse.name} added`);
			}

			console.log(cartResponse);
		} else {

		}
	};

	logout = () => {
		NativeStorage.clearStorage();
		this.props.navigation.navigate('Auth')
	};

	render () {
		const { navigation } = this.props;
		const item = navigation.getParam('item', {});

		return (
			<View style={styles.containerDescription}>
				<View style={styles.imageTitle}>
					<TouchableOpacity
						onPress={() => this.props.navigation.navigate('ProductMap')}
					>
						<Image style={{ width: 25, height: 25 }} source={require('../pics/map.png')}/>
					</TouchableOpacity>
					<Text style={styles.product}>{item.name}</Text>
				</View>
				<Text style={styles.description}>{item.description}</Text>
				<View style={styles.itemContainer}>
					<TouchableOpacity
						onPress={this.handleOpenProductList}
						style={styles.button}>
						<Text style={styles.label}>Products</Text>
					</TouchableOpacity>
					<TouchableOpacity
						onPress={this.handleAddToCart}
						style={styles.button}>
						<Text style={styles.label}>Add to Cart</Text>
					</TouchableOpacity>
					<TouchableOpacity
						onPress={this.logout}
						style={styles.button}>
						<Text style={styles.label}>Logout</Text>
					</TouchableOpacity>
				</View>
				<NetConnectionModal/>
			</View>
		);
	}
}
